#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

PS1='\W > '


# Emacs aliases
alias emacs='systemctl --user enable emacs.service'
alias ekill='emacsclient -e "(kill-emacs)"'  # Kill currently running emacs server
alias remacs='systemctl --user restart emacs'

alias cp='cp -i'
alias mv='mv -i'
alias ln='ln -i'
alias l='ls -tr'
#alias update='pacman -Syu && reboot'
#alias cpd='cp $1 $2 && cd $2'
alias home='cd ~'
alias hdmi='xrandr --output HDMI-A-0 --auto'
alias mnt='doas mount /dev/sda1 /media'
alias netfix='doas systemctl stop wpa_supplicant.service'

alias android='aft-mtp-mount ~/mnt'
alias umnt='doas umount /dev/sda1'

# Directory aliases

alias qubitmd='cd /home/pranay/SpinDynamicsProject/MolecularQubits/MD/V-Complex/'

# Server Aliases

alias alpine='ssh prve7843@login.rc.colorado.edu' # ALPINE HPC CU Boulder
alias fry='ssh pranayvenkatesh@fry.boisestate.edu'


alias nb='newsboat'
alias jn='jupyter-notebook'
alias planckton='conda activate planckton'
alias morphct='conda activate morphct'
alias zotero="./start-zotero.sh"
alias dosa="doas"
#export PATH=$PATH:~/.local/kitty.app/bin
export PATH=$PATH:~/.packages/packmol/
export PATH=$PATH:~/.local/bin
export PATH=$PATH:~/Downloads/packmol/
export PATH=$PATH:/usr/bin/
export PATH=$PATH:~/Downloads/ovito-basic-3.7.5-x86_64/bin/
export PATH=$PATH:~/Downloads/Discord/
export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:~/cordless/
#export PATH=$PATH:/opt/texlive/2019/bin/x86_64-linux
export PATH=$PATH:/opt/texlive/2023/bin/x86_64-linux

#export PATH=$PATH:/usr/local/bin/vmd
#export PATH=$PATH:/usr/local/lib/vmd/plugins/
#export PATH=$PATH:/usr/local/lib/vmd/plugins/include
#export PATH=$PATH:/usr/local/lib/vmd

#export VOTCASHARE=/home/pranay/.miniconda3/pkgs/votca-2022-py39he7848a2_4/share/votca

#export PATH=$PATH:~/.packages/zulip-desktop/

#export LD_LIBRARY_PATH=$LD_LIBRARYPATH:/opt/cuda/lib64
#export CHROME_DRIVER=$CHROME_DRIVER:~/chromedriver/src
#export CONDA_AUTO_ACTIVATE_BASE=false
#export VMDDIR=/usr/local/lib/vmd/plugins  
#export VMD_PLUGIN_INCLUDE_PATH=/usr/local/lib/vmd/plugins/include/
#export VMD_PLUGIN_MOLFILE_PATH=/usr/local/lib/vmd/plugins/LINUXAMD64/molfile/

# BEGIN_KITTY_SHELL_INTEGRATION
#if test -n "$KITTY_INSTALLATION_DIR" -a -e "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; then source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; fi
# END_KITTY_SHELL_INTEGRATION

#conda activate
#. "$HOME/.cargo/env"

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in
    *:/home/pranay/.juliaup/bin:*)
        ;;

    *)
        export PATH=/home/pranay/.juliaup/bin${PATH:+:${PATH}}
        ;;
esac

# <<< juliaup initialize <<<


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/pranay/miniforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/pranay/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/home/pranay/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/home/pranay/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/pranay/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/home/pranay/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

