set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()


Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'preservim/nerdtree'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
"Plugin 'godlygeek/tabular'
Plugin 'JuliaEditorSupport/julia-vim'
"Plugin 'preservim/vim-markdown'
Plugin 'lervag/vimtex'

call vundle#end()
filetype plugin indent on

syntax enable

set background=dark
colorscheme fiendscheme

set encoding=utf-8

set nu

set hlsearch
set incsearch

set wrap
set formatoptions=tcqrn1

"set smartindent
set expandtab
"set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o



"clipboard stuff
set clipboard+=unnamedplus
vmap <F6> :!xclip -f -sel clip<CR>
map <F7> mz:-1r !xclip -o -sel clip<CR>`z

"vimtex stuff

let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_compiler_method = 'latexmk'


